dependent_variables:
- header: {name: BB_bZbZ_1200}
  values:
  - {value: 0}
  - {value: 0.0105779}
  - {value: 0.254188}
independent_variables:
- header: {name: ST, units: GEV}
  values:
  - {low: 1000.0, high: 1250.0}
  - {low: 1250.0, high: 1500.0}
  - {low: 1500.0, high: 2500.0}
