dependent_variables:
- header: {name: TT_tZtZ_1200}
  values:
  - {value: 0.00282109}
  - {value: 0.0977501}
  - {value: 0.0703842}
  - {value: 0.0466084}
  - {value: 0.318464}
  - {value: 0.327617}
  - {value: 6.13734}
independent_variables:
- header: {name: ST, units: GEV}
  values:
  - {low: 1000.0, high: 1120.0}
  - {low: 1120.0, high: 1240.0}
  - {low: 1240.0, high: 1360.0}
  - {low: 1360.0, high: 1480.0}
  - {low: 1480.0, high: 1660.0}
  - {low: 1660.0, high: 1780.0}
  - {low: 1780.0, high: 2500.0}
